# -*- coding: utf-8 -*-
"""Fraud_Detection_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_4dhRCQKuF-Dptu2ayzSxZ20s-hzoom
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("creditcard.csv")

"""##Exploring the Data"""

df.head()

df.info()

df.shape

df.describe()

df.duplicated().sum()

df.isnull().sum()

df['Class'].value_counts(normalize=True)



"""##Cleaning"""

df = df.drop_duplicates()

df.duplicated().sum()

x = df.drop('Class', axis=1)
y = df['Class']

"""##Split Train/Test"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, stratify= y, random_state= 42)

"""##Scale Column"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train['Amount'] = scaler.fit_transform(x_train[['Amount']])
x_test['Amount'] = scaler.fit_transform(x_test[['Amount']])